/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomImage: typeof import('./src/components/custom-image/custom-image.vue')['default']
    CustomPage: typeof import('./src/components/custom-page/custom-page.vue')['default']
    CustomPicker: typeof import('./src/components/custom-picker/custom-picker.vue')['default']
    EchartCanvas: typeof import('./src/components/echart-canvas/echart-canvas.vue')['default']
    Navbar: typeof import('./src/components/navbar/navbar.vue')['default']
    NoData: typeof import('./src/components/no-data/no-data.vue')['default']
    NoticeSwiper: typeof import('./src/components/notice-swiper/notice-swiper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollSwiperTab: typeof import('./src/components/scroll-swiper-tab/scroll-swiper-tab.vue')['default']
    StickyView: typeof import('./src/components/sticky-view/sticky-view.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/tabbar.vue')['default']
    TransparentNavbar: typeof import('./src/components/transparent-navbar/transparent-navbar.vue')['default']
  }
}
